# OTLP gRPC endpoint to send the collected metrics
endpoint:
  address: "example-opentelemetry-collector.default"

debug:
  enabled: true
  storeMinidump: true
  # This will send a metric when the collector exits unexpectedly, useful to detect crashes and restarts
  # The metric will be sent to the address and port defined in the endpoint section
  # The port is defined as integer, but it should be quoted since it will be put to containers' env
  sendUnplannedExitMetric: true
