name: Integration Tests

on:
  push:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull Docker images
        run: |
          docker compose -f docker compose-tests.yml pull

      - name: Start services using Docker Compose
        run: |
          docker compose -f docker compose-tests.yml up -d

      - name: Wait for services to be ready
        run: |
          # Implement your service readiness checks here
          #./scripts/wait-for-services.sh
          #sleep 50

      - name: Run trace-based tests
        run: |
          make run-tracetesting

      - name: Stop services
        if: always()
        run: |
          docker compose -f docker compose-tests.yml down
