name: Integration Tests

on:
  workflow_run:
    workflows: ["Generate Images"]  # Name of the build_images workflow
    types:
      - completed
jobs:
  run_tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "Run CI"
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: run tracetesting
        run: |
          make build && docker system prune -f
          sleep 500
          make run-tracetesting
