# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Integration Tests

on:
  workflow_run:
    workflows: ["Generate Images"]  # Name of the build_images workflow
    types:
      - completed

jobs:
  run_tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: "Run CI"
#    if: github.event.review.state == 'APPROVED'
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: run tracetesting
        run: |
          make build && docker system prune -f && make run-tracetesting
