name: Integration Tests

on:
  push:

    branches: [ main ]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: "Run CI"
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: run tracetesting
        run: |
          make build && docker system prune -f
          sleep 500
          make run-tracetesting
